twig:
  default_path: "%kernel.project_dir%/templates"
  #  form_theme:
  #     bootstrap_4_layout.html.twig

  form_themes: ["bootstrap_4_layout.html.twig"]

  globals:
    categoryRepository: "@App\\Repository\\CategoryRepository"
    cartService: "@App\\Cart\\CartService"
